project_id = "rzmxhcebsdsyrzdkipct"

[functions.upload-properties]
verify_jwt = false

[functions.geocode]
verify_jwt = false

[functions.upload-log]
verify_jwt = false

[functions.analyze-property]
verify_jwt = false